"""
Export endpoint: POST /api/export

Exports a conversation or a single answer as plain text or formatted text.
Used by the frontend "Export" button.

No PDF library dependency — generates a plain-text document with headers
that can be copied, saved, or printed from the browser's print dialog.
"""
import logging
from datetime import datetime
from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel
from typing import Optional, List
from app.routes.deps import get_current_user
from app.database.mongodb import conversations_col, messages_col

router = APIRouter(prefix="/api", tags=["export"])
logger = logging.getLogger("doj_rag.routes.export")


class ExportRequest(BaseModel):
    conversation_id: str
    format: Optional[str] = "txt"  # "txt" or "md"


@router.post("/export")
async def export_conversation(
    req: ExportRequest,
    current_user: dict = Depends(get_current_user)
):
    """Export a full conversation as plain text or Markdown."""
    conv = conversations_col().find_one({"conversation_id": req.conversation_id})
    if not conv:
        raise HTTPException(status_code=404, detail="Conversation not found.")
    if conv.get("user_id") != current_user["user_id"]:
        raise HTTPException(status_code=403, detail="Access denied.")

    messages = list(
        messages_col()
        .find({"conversation_id": req.conversation_id})
        .sort("created_at", 1)
    )

    title = conv.get("title", "Conversation")
    created = conv.get("created_at", datetime.utcnow())
    if hasattr(created, "strftime"):
        created_str = created.strftime("%Y-%m-%d %H:%M UTC")
    else:
        created_str = str(created)

    if req.format == "md":
        lines = [
            f"# {title}",
            f"**Exported:** {created_str}",
            f"**Judiciary AI — DOJ-RAG Legal Assistant**",
            "",
            "---",
            "",
        ]
        for msg in messages:
            sender = "**You**" if msg["sender"] == "user" else "**Judiciary AI**"
            lang = msg.get("language", "")
            lang_tag = f" _{lang}_" if lang and lang != "English" else ""
            lines.append(f"{sender}{lang_tag}:")
            lines.append("")
            lines.append(msg.get("message", ""))
            lines.append("")
            sources = msg.get("sources") or []
            if sources:
                lines.append("**Sources:**")
                for s in sources:
                    parts = []
                    if s.get("document"):
                        parts.append(s["document"])
                    if s.get("article"):
                        parts.append(f"Art. {s['article']}")
                    elif s.get("section"):
                        parts.append(f"Sec. {s['section']}")
                    elif s.get("rule"):
                        parts.append(f"Rule {s['rule']}")
                    if parts:
                        lines.append(f"- {' — '.join(parts)}")
                lines.append("")
            lines.append("---")
            lines.append("")

        content = "\n".join(lines)
        filename = f"judiciary_ai_{req.conversation_id[:8]}.md"
    else:
        # Plain text format
        lines = [
            "=" * 60,
            f"JUDICIARY AI — DOJ-RAG LEGAL ASSISTANT",
            f"Conversation: {title}",
            f"Exported: {created_str}",
            "=" * 60,
            "",
        ]
        for msg in messages:
            sender = "YOU" if msg["sender"] == "user" else "JUDICIARY AI"
            lang = msg.get("language", "")
            lang_note = f" [{lang}]" if lang and lang not in ("English", "auto", "") else ""
            lines.append(f"{'─' * 40}")
            lines.append(f"[{sender}{lang_note}]")
            lines.append("")
            lines.append(msg.get("message", ""))
            sources = msg.get("sources") or []
            if sources:
                lines.append("")
                lines.append("Sources:")
                for s in sources:
                    parts = []
                    if s.get("document"):
                        parts.append(s["document"])
                    if s.get("article"):
                        parts.append(f"Article {s['article']}")
                    elif s.get("section"):
                        parts.append(f"Section {s['section']}")
                    if parts:
                        lines.append(f"  • {' — '.join(parts)}")
            lines.append("")

        lines.append("=" * 60)
        lines.append("Generated by Judiciary AI (DOJ-RAG) — For reference only.")
        lines.append("Always verify legal information with a qualified legal professional.")
        lines.append("=" * 60)

        content = "\n".join(lines)
        filename = f"judiciary_ai_{req.conversation_id[:8]}.txt"

    return PlainTextResponse(
        content=content,
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "Content-Type": "text/plain; charset=utf-8",
        }
    )
