import React, { createContext, useContext, useEffect, useState } from "react";

export const UI_LANGUAGES = [
  "Auto-Detect", "English", "Hindi", "Tamil", "Urdu", "Punjabi", "Odia",
  "Telugu", "Kannada", "Malayalam", "Bengali", "Marathi", "Gujarati",
];

const NATIVE_NAMES = {
  English: "English",
  Hindi: "हिन्दी",
  Tamil: "தமிழ்",
  Urdu: "اردو",
  Punjabi: "ਪੰਜਾਬੀ",
  Odia: "ଓଡ଼ିଆ",
  Telugu: "తెలుగు",
  Kannada: "ಕನ್ನಡ",
  Malayalam: "മലയാളം",
  Bengali: "বাংলা",
  Marathi: "मराठी",
  Gujarati: "ગુજરાતી",
};

const COPY = {
  English: {
    loading: "Loading…", legalAssistant: "Legal Assistant", newConversation: "New conversation",
    emptyConversations: "No conversations yet. Ask a legal question to begin.", signedIn: "Signed in", logout: "Log out",
    disclaimer: "Answers are generated from retrieved legal text in your processed documents. Verify against the original source for formal use.",
    voice: "Voice", autoSpeak: "Auto-speak", export: "↓ Export", clear: "Clear", downloadConversation: "Download conversation as TXT",
    welcomeTitle: "AI Judiciary Legal Assistant", welcomeDescription: "Ask about Indian law, legal documents, or everyday topics.",
    p19Title: "Article 19: Freedom of Speech", p19Desc: "Six freedoms and their constitutional restrictions",
    p14Title: "Article 14: Right to Equality", p14Desc: "Equal protection and non-discrimination",
    p21Title: "Article 21: Life and Liberty", p21Desc: "Protection of life, liberty, and privacy",
    p32Title: "Article 32: Constitutional Remedies", p32Desc: "Supreme Court writs and constitutional remedies",
    pTamilTitle: "Article 19 in Tamil (சரத்து 19)", pTamilDesc: "Freedom of speech and six fundamental rights",
    pTeluguTitle: "Article 19 in Telugu (19వ అధికరణం)", pTeluguDesc: "Freedom of speech and six fundamental rights",
    nlpActive: "Multilingual legal NLP is ready", editingPrevious: "Editing a previous message. Sending will replace everything after it.",
    cancel: "Cancel", stopRecording: "Stop recording", startRecording: "Start recording", askByVoice: "Ask by voice",
    inputPlaceholder: "Ask a question about law or anything else…", stopGenerating: "Stop generating", send: "Send",
    generating: "Generating a response. You can stop it or edit your message to interrupt.", recording: "Recording… tap the microphone again to stop and transcribe.",
    copy: "⧉ Copy", copied: "✓ Copied", responseTime: "Response time", detectedIntent: "Detected intent",
    editResend: "Edit and resend", editMessage: "Edit message", language: "Language", hideSource: "Hide source", viewSource: "View source",
    exportConversation: "Export conversation", listen: "Listen to audio", stopPlayback: "Stop audio playback", replay: "Replay audio from beginning",
    relatedProvisions: "Related provisions", reference: "Reference", article: "Article", section: "Section", rule: "Rule",
    languageSelector: "Dashboard and response language", manualOverride: "Manual answer language: {language}", autoDetectTitle: "Auto-detect answer language from each message", reset: "Reset to Auto-Detect",
    signInTitle: "Sign in to your account", username: "Username", password: "Password", signingIn: "Signing in…", signIn: "Sign in",
    noAccount: "Don't have an account?", register: "Register", createAccount: "Create your account", privateHistory: "Your conversation history stays private to your account",
    emailOptional: "Email (optional)", confirmPassword: "Confirm password", passwordMismatch: "Passwords do not match.", passwordMin: "Password must be at least 6 characters.",
    creatingAccount: "Creating account…", alreadyAccount: "Already have an account?", errorLoad: "Could not load that conversation.", errorDelete: "Could not delete that conversation.",
    errorUpdate: "Could not update the conversation before resending.", errorEmptyExport: "Send a message before exporting this conversation.", errorExport: "Failed to export conversation.", errorTranscribe: "Could not transcribe audio.",
  },
  Hindi: {
    loading: "लोड हो रहा है…", legalAssistant: "कानूनी सहायक", newConversation: "नई बातचीत", emptyConversations: "अभी कोई बातचीत नहीं है। शुरू करने के लिए कानूनी सवाल पूछें।", signedIn: "साइन इन है", logout: "लॉग आउट",
    disclaimer: "जवाब आपके संसाधित दस्तावेज़ों के कानूनी पाठ पर आधारित हैं। औपचारिक उपयोग से पहले मूल स्रोत से जाँचें।", voice: "आवाज़", autoSpeak: "जवाब बोलें", export: "↓ निर्यात", clear: "साफ़ करें", downloadConversation: "बातचीत TXT में डाउनलोड करें",
    welcomeTitle: "AI न्यायिक कानूनी सहायक", welcomeDescription: "भारतीय कानून, कानूनी दस्तावेज़ों या रोज़मर्रा के विषयों के बारे में पूछें।", p19Title: "अनुच्छेद 19: अभिव्यक्ति की स्वतंत्रता", p19Desc: "छह स्वतंत्रताएँ और उन पर संवैधानिक प्रतिबंध",
    p14Title: "अनुच्छेद 14: समानता का अधिकार", p14Desc: "कानून का समान संरक्षण और भेदभाव का निषेध", p21Title: "अनुच्छेद 21: जीवन और स्वतंत्रता", p21Desc: "जीवन, स्वतंत्रता और निजता की सुरक्षा",
    p32Title: "अनुच्छेद 32: संवैधानिक उपचार", p32Desc: "सर्वोच्च न्यायालय की रिट और संवैधानिक उपचार", pTamilTitle: "अनुच्छेद 19 तमिल में (சரத்து 19)", pTamilDesc: "अभिव्यक्ति की स्वतंत्रता और छह मौलिक अधिकार",
    pTeluguTitle: "अनुच्छेद 19 तेलुगु में (19వ అధికరణం)", pTeluguDesc: "अभिव्यक्ति की स्वतंत्रता और छह मौलिक अधिकार", nlpActive: "बहुभाषी कानूनी NLP तैयार है", editingPrevious: "पुराना संदेश संपादित हो रहा है। भेजने पर इसके बाद के संदेश बदल जाएंगे।",
    cancel: "रद्द करें", stopRecording: "रिकॉर्डिंग रोकें", startRecording: "रिकॉर्डिंग शुरू करें", askByVoice: "बोलकर पूछें", inputPlaceholder: "कानून या किसी अन्य विषय पर सवाल पूछें…", stopGenerating: "जवाब बनाना रोकें", send: "भेजें",
    generating: "जवाब तैयार हो रहा है। रोकने या बीच में रोकने के लिए अपना संदेश संपादित करने का विकल्प है।", recording: "रिकॉर्डिंग… रोकने और लिखित रूप पाने के लिए माइक्रोफ़ोन फिर दबाएँ।", copy: "⧉ कॉपी", copied: "✓ कॉपी हुआ", responseTime: "जवाब का समय", detectedIntent: "पहचाना गया उद्देश्य",
    editResend: "संपादित करके फिर भेजें", editMessage: "संदेश संपादित करें", language: "भाषा", hideSource: "स्रोत छिपाएँ", viewSource: "स्रोत देखें", exportConversation: "बातचीत निर्यात करें", listen: "ऑडियो सुनें", stopPlayback: "ऑडियो रोकें", replay: "शुरू से फिर सुनें",
    relatedProvisions: "संबंधित प्रावधान", reference: "संदर्भ", article: "अनुच्छेद", section: "धारा", rule: "नियम", languageSelector: "डैशबोर्ड और जवाब की भाषा", manualOverride: "जवाब की चुनी हुई भाषा: {language}", autoDetectTitle: "हर संदेश की भाषा अपने-आप पहचानें", reset: "अपने-आप पहचान पर लौटें",
    signInTitle: "अपने खाते में साइन इन करें", username: "उपयोगकर्ता नाम", password: "पासवर्ड", signingIn: "साइन इन हो रहा है…", signIn: "साइन इन", noAccount: "खाता नहीं है?", register: "रजिस्टर करें", createAccount: "अपना खाता बनाएँ", privateHistory: "आपकी बातचीत का इतिहास केवल आपके खाते में सुरक्षित रहता है", emailOptional: "ईमेल (वैकल्पिक)", confirmPassword: "पासवर्ड की पुष्टि करें", passwordMismatch: "पासवर्ड मेल नहीं खाते।", passwordMin: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।", creatingAccount: "खाता बनाया जा रहा है…", alreadyAccount: "पहले से खाता है?", errorLoad: "बातचीत लोड नहीं हो सकी।", errorDelete: "बातचीत हटाई नहीं जा सकी।", errorUpdate: "फिर से भेजने से पहले बातचीत अपडेट नहीं हो सकी।", errorEmptyExport: "निर्यात करने से पहले संदेश भेजें।", errorExport: "बातचीत निर्यात नहीं हो सकी।", errorTranscribe: "ऑडियो को लिखित रूप में नहीं बदला जा सका।",
  },
  Tamil: {
    loading: "ஏற்றப்படுகிறது…", legalAssistant: "சட்ட உதவியாளர்", newConversation: "புதிய உரையாடல்", emptyConversations: "இன்னும் உரையாடல்கள் இல்லை. தொடங்க சட்டக் கேள்வியைக் கேளுங்கள்.", signedIn: "உள்நுழைந்துள்ளீர்கள்", logout: "வெளியேறு",
    disclaimer: "பதில்கள் உங்கள் செயலாக்கப்பட்ட ஆவணங்களிலிருந்து பெறப்பட்ட சட்டத் தகவல்களை அடிப்படையாகக் கொண்டவை. அதிகாரப்பூர்வ பயன்பாட்டிற்கு முன் மூல ஆவணத்தைச் சரிபார்க்கவும்.", voice: "குரல்", autoSpeak: "பதிலைப் படிக்கவும்", export: "↓ ஏற்றுமதி", clear: "அழி", downloadConversation: "உரையாடலை TXT ஆகப் பதிவிறக்கு",
    welcomeTitle: "AI நீதித்துறை சட்ட உதவியாளர்", welcomeDescription: "இந்தியச் சட்டம், சட்ட ஆவணங்கள் அல்லது அன்றாடத் தலைப்புகள் பற்றி கேளுங்கள்.", p19Title: "சரத்து 19: பேச்சுச் சுதந்திரம்", p19Desc: "ஆறு சுதந்திரங்களும் அவற்றுக்கான அரசியலமைப்புக் கட்டுப்பாடுகளும்", p14Title: "சரத்து 14: சமத்துவ உரிமை", p14Desc: "சட்டத்தின் சம பாதுகாப்பும் பாகுபாடு தடுப்பும்",
    p21Title: "சரத்து 21: வாழ்வும் சுதந்திரமும்", p21Desc: "வாழ்வு, சுதந்திரம் மற்றும் தனியுரிமைக்கான பாதுகாப்பு", p32Title: "சரத்து 32: அரசியலமைப்புத் தீர்வுகள்", p32Desc: "உச்சநீதிமன்ற ரிட் மனுக்கள் மற்றும் அரசியலமைப்புத் தீர்வுகள்", pTamilTitle: "சரத்து 19 தமிழில்", pTamilDesc: "பேச்சுச் சுதந்திரமும் ஆறு அடிப்படை உரிமைகளும்",
    pTeluguTitle: "சரத்து 19 தெலுங்கில் (19వ అధికరణం)", pTeluguDesc: "பேச்சுச் சுதந்திரமும் ஆறு அடிப்படை உரிமைகளும்", nlpActive: "பல்மொழிச் சட்ட NLP தயார்", editingPrevious: "முந்தைய செய்தியைத் திருத்துகிறீர்கள். அனுப்பினால் அதற்குப் பிந்தைய செய்திகள் மாற்றப்படும்.", cancel: "ரத்து செய்", stopRecording: "பதிவை நிறுத்து", startRecording: "பதிவைத் தொடங்கு", askByVoice: "குரலில் கேளுங்கள்",
    inputPlaceholder: "சட்டம் அல்லது வேறு எந்தத் தலைப்பைப் பற்றியும் கேளுங்கள்…", stopGenerating: "பதில் உருவாக்குவதை நிறுத்து", send: "அனுப்பு", generating: "பதில் உருவாகிறது. நிறுத்தலாம் அல்லது செய்தியைத் திருத்தி இடைநிறுத்தலாம்.", recording: "பதிவு செய்கிறது… நிறுத்தி உரையாக மாற்ற மைக்கை மீண்டும் தட்டவும்.", copy: "⧉ நகலெடு", copied: "✓ நகலெடுக்கப்பட்டது", responseTime: "பதில் நேரம்", detectedIntent: "கண்டறிந்த நோக்கம்",
    editResend: "திருத்தி மீண்டும் அனுப்பு", editMessage: "செய்தியைத் திருத்து", language: "மொழி", hideSource: "ஆதாரத்தை மறை", viewSource: "ஆதாரத்தைக் காண்க", exportConversation: "உரையாடலை ஏற்றுமதி செய்", listen: "ஒலியைக் கேள்", stopPlayback: "ஒலியை நிறுத்து", replay: "மீண்டும் கேள்", relatedProvisions: "தொடர்புடைய சட்டப் பிரிவுகள்", reference: "குறிப்பு", article: "சரத்து", section: "பிரிவு", rule: "விதி",
    languageSelector: "டாஷ்போர்டு மற்றும் பதில் மொழி", manualOverride: "பதில் மொழி: {language}", autoDetectTitle: "ஒவ்வொரு செய்தியின் மொழியையும் தானாகக் கண்டறி", reset: "தானியங்கு கண்டறிதலுக்குத் திரும்பு", signInTitle: "உங்கள் கணக்கில் உள்நுழைக", username: "பயனர்பெயர்", password: "கடவுச்சொல்", signingIn: "உள்நுழைகிறது…", signIn: "உள்நுழை", noAccount: "கணக்கு இல்லையா?", register: "பதிவு செய்க", createAccount: "கணக்கை உருவாக்கு", privateHistory: "உங்கள் உரையாடல் வரலாறு உங்கள் கணக்கில் தனிப்பட்டதாக இருக்கும்", emailOptional: "மின்னஞ்சல் (விருப்பம்)", confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்து", passwordMismatch: "கடவுச்சொற்கள் பொருந்தவில்லை.", passwordMin: "கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்.", creatingAccount: "கணக்கு உருவாகிறது…", alreadyAccount: "ஏற்கனவே கணக்கு உள்ளதா?", errorLoad: "உரையாடலை ஏற்ற முடியவில்லை.", errorDelete: "உரையாடலை நீக்க முடியவில்லை.", errorUpdate: "மீண்டும் அனுப்புவதற்கு முன் உரையாடலைப் புதுப்பிக்க முடியவில்லை.", errorEmptyExport: "ஏற்றுமதி செய்வதற்கு முன் ஒரு செய்தியை அனுப்புங்கள்.", errorExport: "உரையாடலை ஏற்றுமதி செய்ய முடியவில்லை.", errorTranscribe: "ஒலியை உரையாக மாற்ற முடியவில்லை.",
  },
  Urdu: {
    loading: "لوڈ ہو رہا ہے…", legalAssistant: "قانونی معاون", newConversation: "نئی گفتگو", emptyConversations: "ابھی کوئی گفتگو نہیں۔ شروع کرنے کے لیے قانونی سوال پوچھیں۔", signedIn: "سائن اِن ہیں", logout: "لاگ آؤٹ",
    disclaimer: "جوابات آپ کی تیار کردہ دستاویزات سے حاصل کردہ قانونی متن پر مبنی ہیں۔ رسمی استعمال سے پہلے اصل ماخذ کی تصدیق کریں۔", voice: "آواز", autoSpeak: "جواب سنائیں", export: "↓ برآمد", clear: "صاف کریں", downloadConversation: "گفتگو TXT میں ڈاؤن لوڈ کریں",
    welcomeTitle: "AI عدالتی قانونی معاون", welcomeDescription: "بھارتی قانون، قانونی دستاویزات یا روزمرہ موضوعات کے بارے میں پوچھیں۔", p19Title: "آرٹیکل 19: اظہارِ رائے کی آزادی", p19Desc: "چھ آزادیاں اور ان پر آئینی پابندیاں", p14Title: "آرٹیکل 14: مساوات کا حق", p14Desc: "قانون کا مساوی تحفظ اور امتیاز کی ممانعت",
    p21Title: "آرٹیکل 21: زندگی اور آزادی", p21Desc: "زندگی، آزادی اور رازداری کا تحفظ", p32Title: "آرٹیکل 32: آئینی چارہ جوئی", p32Desc: "سپریم کورٹ کی رِٹ اور آئینی چارہ جوئی", pTamilTitle: "آرٹیکل 19 تمل میں", pTamilDesc: "اظہارِ رائے کی آزادی اور چھ بنیادی حقوق", pTeluguTitle: "آرٹیکل 19 تیلگو میں", pTeluguDesc: "اظہارِ رائے کی آزادی اور چھ بنیادی حقوق",
    nlpActive: "کثیر لسانی قانونی NLP تیار ہے", editingPrevious: "پچھلا پیغام ترمیم ہو رہا ہے۔ بھیجنے سے اس کے بعد کے پیغامات بدل جائیں گے۔", cancel: "منسوخ", stopRecording: "ریکارڈنگ روکیں", startRecording: "ریکارڈنگ شروع کریں", askByVoice: "آواز سے پوچھیں", inputPlaceholder: "قانون یا کسی بھی دوسرے موضوع کے بارے میں پوچھیں…", stopGenerating: "جواب بنانا روکیں", send: "بھیجیں", generating: "جواب تیار ہو رہا ہے۔ آپ اسے روک سکتے ہیں یا پیغام میں ترمیم کر کے درمیان میں روک سکتے ہیں۔", recording: "ریکارڈنگ… روکنے اور نقلِ تحریر کے لیے مائیک دوبارہ دبائیں۔", copy: "⧉ نقل کریں", copied: "✓ نقل ہو گیا", responseTime: "جواب کا وقت", detectedIntent: "معلوم شدہ مقصد",
    editResend: "ترمیم کر کے دوبارہ بھیجیں", editMessage: "پیغام میں ترمیم", language: "زبان", hideSource: "ماخذ چھپائیں", viewSource: "ماخذ دیکھیں", exportConversation: "گفتگو برآمد کریں", listen: "آڈیو سنیں", stopPlayback: "آڈیو روکیں", replay: "دوبارہ سنیں", relatedProvisions: "متعلقہ دفعات", reference: "حوالہ", article: "آرٹیکل", section: "دفعہ", rule: "قاعدہ", languageSelector: "ڈیش بورڈ اور جواب کی زبان", manualOverride: "جواب کی زبان: {language}", autoDetectTitle: "ہر پیغام کی زبان خودکار طور پر پہچانیں", reset: "خودکار شناخت پر واپس جائیں",
    signInTitle: "اپنے اکاؤنٹ میں سائن اِن کریں", username: "صارف نام", password: "پاس ورڈ", signingIn: "سائن اِن ہو رہا ہے…", signIn: "سائن اِن", noAccount: "اکاؤنٹ نہیں ہے؟", register: "رجسٹر کریں", createAccount: "اپنا اکاؤنٹ بنائیں", privateHistory: "آپ کی گفتگو کی تاریخ صرف آپ کے اکاؤنٹ میں محفوظ ہے", emailOptional: "ای میل (اختیاری)", confirmPassword: "پاس ورڈ کی تصدیق", passwordMismatch: "پاس ورڈ مطابقت نہیں رکھتے۔", passwordMin: "پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے۔", creatingAccount: "اکاؤنٹ بن رہا ہے…", alreadyAccount: "پہلے سے اکاؤنٹ ہے؟", errorLoad: "گفتگو لوڈ نہیں ہو سکی۔", errorDelete: "گفتگو حذف نہیں ہو سکی۔", errorUpdate: "دوبارہ بھیجنے سے پہلے گفتگو اپ ڈیٹ نہیں ہو سکی۔", errorEmptyExport: "برآمد کرنے سے پہلے پیغام بھیجیں۔", errorExport: "گفتگو برآمد نہیں ہو سکی۔", errorTranscribe: "آڈیو نقل نہیں ہو سکی۔",
  },
  Punjabi: {
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…", legalAssistant: "ਕਾਨੂੰਨੀ ਸਹਾਇਕ", newConversation: "ਨਵੀਂ ਗੱਲਬਾਤ", emptyConversations: "ਹਾਲੇ ਕੋਈ ਗੱਲਬਾਤ ਨਹੀਂ। ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਕਾਨੂੰਨੀ ਸਵਾਲ ਪੁੱਛੋ।", signedIn: "ਸਾਈਨ ਇਨ ਹੈ", logout: "ਲੌਗ ਆਉਟ",
    disclaimer: "ਜਵਾਬ ਤੁਹਾਡੇ ਪ੍ਰਕਿਰਿਆ ਕੀਤੇ ਦਸਤਾਵੇਜ਼ਾਂ ਦੇ ਕਾਨੂੰਨੀ ਪਾਠ ਤੋਂ ਤਿਆਰ ਹੁੰਦੇ ਹਨ। ਰਸਮੀ ਵਰਤੋਂ ਤੋਂ ਪਹਿਲਾਂ ਮੂਲ ਸਰੋਤ ਦੀ ਜਾਂਚ ਕਰੋ।", voice: "ਆਵਾਜ਼", autoSpeak: "ਜਵਾਬ ਬੋਲੋ", export: "↓ ਨਿਰਯਾਤ", clear: "ਸਾਫ਼ ਕਰੋ", downloadConversation: "ਗੱਲਬਾਤ TXT ਵਜੋਂ ਡਾਊਨਲੋਡ ਕਰੋ",
    welcomeTitle: "AI ਨਿਆਂਇਕ ਕਾਨੂੰਨੀ ਸਹਾਇਕ", welcomeDescription: "ਭਾਰਤੀ ਕਾਨੂੰਨ, ਕਾਨੂੰਨੀ ਦਸਤਾਵੇਜ਼ਾਂ ਜਾਂ ਰੋਜ਼ਾਨਾ ਵਿਸ਼ਿਆਂ ਬਾਰੇ ਪੁੱਛੋ।", p19Title: "ਧਾਰਾ 19: ਬੋਲਣ ਦੀ ਆਜ਼ਾਦੀ", p19Desc: "ਛੇ ਆਜ਼ਾਦੀਆਂ ਅਤੇ ਉਨ੍ਹਾਂ ਉੱਤੇ ਸੰਵਿਧਾਨਕ ਪਾਬੰਦੀਆਂ", p14Title: "ਧਾਰਾ 14: ਬਰਾਬਰੀ ਦਾ ਹੱਕ", p14Desc: "ਕਾਨੂੰਨ ਦੀ ਬਰਾਬਰ ਸੁਰੱਖਿਆ ਅਤੇ ਭੇਦਭਾਵ ਦੀ ਮਨਾਹੀ",
    p21Title: "ਧਾਰਾ 21: ਜੀਵਨ ਅਤੇ ਆਜ਼ਾਦੀ", p21Desc: "ਜੀਵਨ, ਆਜ਼ਾਦੀ ਅਤੇ ਨਿੱਜਤਾ ਦੀ ਸੁਰੱਖਿਆ", p32Title: "ਧਾਰਾ 32: ਸੰਵਿਧਾਨਕ ਉਪਾਅ", p32Desc: "ਸੁਪਰੀਮ ਕੋਰਟ ਦੀਆਂ ਰਿੱਟਾਂ ਅਤੇ ਸੰਵਿਧਾਨਕ ਉਪਾਅ", pTamilTitle: "ਧਾਰਾ 19 ਤਮਿਲ ਵਿੱਚ", pTamilDesc: "ਬੋਲਣ ਦੀ ਆਜ਼ਾਦੀ ਅਤੇ ਛੇ ਮੌਲਿਕ ਹੱਕ", pTeluguTitle: "ਧਾਰਾ 19 ਤੇਲਗੂ ਵਿੱਚ", pTeluguDesc: "ਬੋਲਣ ਦੀ ਆਜ਼ਾਦੀ ਅਤੇ ਛੇ ਮੌਲਿਕ ਹੱਕ",
    nlpActive: "ਬਹੁ-ਭਾਸ਼ਾਈ ਕਾਨੂੰਨੀ NLP ਤਿਆਰ ਹੈ", editingPrevious: "ਪਿਛਲਾ ਸੁਨੇਹਾ ਸੋਧਿਆ ਜਾ ਰਿਹਾ ਹੈ। ਭੇਜਣ ਨਾਲ ਇਸ ਤੋਂ ਬਾਅਦ ਦੇ ਸੁਨੇਹੇ ਬਦਲ ਜਾਣਗੇ।", cancel: "ਰੱਦ ਕਰੋ", stopRecording: "ਰਿਕਾਰਡਿੰਗ ਰੋਕੋ", startRecording: "ਰਿਕਾਰਡਿੰਗ ਸ਼ੁਰੂ ਕਰੋ", askByVoice: "ਬੋਲ ਕੇ ਪੁੱਛੋ", inputPlaceholder: "ਕਾਨੂੰਨ ਜਾਂ ਕਿਸੇ ਵੀ ਹੋਰ ਵਿਸ਼ੇ ਬਾਰੇ ਪੁੱਛੋ…", stopGenerating: "ਜਵਾਬ ਬਣਾਉਣਾ ਰੋਕੋ", send: "ਭੇਜੋ", generating: "ਜਵਾਬ ਤਿਆਰ ਹੋ ਰਿਹਾ ਹੈ। ਤੁਸੀਂ ਇਸਨੂੰ ਰੋਕ ਸਕਦੇ ਹੋ ਜਾਂ ਸੁਨੇਹਾ ਸੋਧ ਕੇ ਵਿਚਕਾਰ ਰੋਕ ਸਕਦੇ ਹੋ।", recording: "ਰਿਕਾਰਡਿੰਗ… ਰੋਕਣ ਅਤੇ ਲਿਖਤ ਬਣਾਉਣ ਲਈ ਮਾਈਕ ਦੁਬਾਰਾ ਦਬਾਓ।", copy: "⧉ ਕਾਪੀ ਕਰੋ", copied: "✓ ਕਾਪੀ ਹੋ ਗਿਆ", responseTime: "ਜਵਾਬ ਦਾ ਸਮਾਂ", detectedIntent: "ਪਛਾਣਿਆ ਮਕਸਦ",
    editResend: "ਸੋਧ ਕੇ ਦੁਬਾਰਾ ਭੇਜੋ", editMessage: "ਸੁਨੇਹਾ ਸੋਧੋ", language: "ਭਾਸ਼ਾ", hideSource: "ਸਰੋਤ ਲੁਕਾਓ", viewSource: "ਸਰੋਤ ਵੇਖੋ", exportConversation: "ਗੱਲਬਾਤ ਨਿਰਯਾਤ ਕਰੋ", listen: "ਆਡੀਓ ਸੁਣੋ", stopPlayback: "ਆਡੀਓ ਰੋਕੋ", replay: "ਮੁੜ ਸੁਣੋ", relatedProvisions: "ਸੰਬੰਧਿਤ ਧਾਰਾਵਾਂ", reference: "ਹਵਾਲਾ", article: "ਧਾਰਾ", section: "ਸੈਕਸ਼ਨ", rule: "ਨਿਯਮ", languageSelector: "ਡੈਸ਼ਬੋਰਡ ਅਤੇ ਜਵਾਬ ਦੀ ਭਾਸ਼ਾ", manualOverride: "ਜਵਾਬ ਦੀ ਭਾਸ਼ਾ: {language}", autoDetectTitle: "ਹਰੇਕ ਸੁਨੇਹੇ ਦੀ ਭਾਸ਼ਾ ਆਪਣੇ-ਆਪ ਪਛਾਣੋ", reset: "ਆਟੋ-ਡਿਟੈਕਟ ਤੇ ਵਾਪਸ ਜਾਓ",
    signInTitle: "ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ", username: "ਯੂਜ਼ਰਨੇਮ", password: "ਪਾਸਵਰਡ", signingIn: "ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ…", signIn: "ਸਾਈਨ ਇਨ", noAccount: "ਖਾਤਾ ਨਹੀਂ ਹੈ?", register: "ਰਜਿਸਟਰ ਕਰੋ", createAccount: "ਆਪਣਾ ਖਾਤਾ ਬਣਾਓ", privateHistory: "ਤੁਹਾਡੀ ਗੱਲਬਾਤ ਦਾ ਇਤਿਹਾਸ ਤੁਹਾਡੇ ਖਾਤੇ ਤੱਕ ਨਿੱਜੀ ਰਹਿੰਦਾ ਹੈ", emailOptional: "ਈਮੇਲ (ਵਿਕਲਪਿਕ)", confirmPassword: "ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ", passwordMismatch: "ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ।", passwordMin: "ਪਾਸਵਰਡ ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।", creatingAccount: "ਖਾਤਾ ਬਣ ਰਿਹਾ ਹੈ…", alreadyAccount: "ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?", errorLoad: "ਗੱਲਬਾਤ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀ।", errorDelete: "ਗੱਲਬਾਤ ਮਿਟਾਈ ਨਹੀਂ ਜਾ ਸਕੀ।", errorUpdate: "ਦੁਬਾਰਾ ਭੇਜਣ ਤੋਂ ਪਹਿਲਾਂ ਗੱਲਬਾਤ ਅੱਪਡੇਟ ਨਹੀਂ ਹੋ ਸਕੀ।", errorEmptyExport: "ਨਿਰਯਾਤ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਸੁਨੇਹਾ ਭੇਜੋ।", errorExport: "ਗੱਲਬਾਤ ਨਿਰਯਾਤ ਨਹੀਂ ਹੋ ਸਕੀ।", errorTranscribe: "ਆਡੀਓ ਨੂੰ ਲਿਖਤ ਵਿੱਚ ਨਹੀਂ ਬਦਲ ਸਕੇ।",
  },
  Odia: {
    loading: "ଲୋଡ୍ ହେଉଛି…", legalAssistant: "ଆଇନ ସହାୟକ", newConversation: "ନୂଆ କଥାବାର୍ତ୍ତା", emptyConversations: "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି କଥାବାର୍ତ୍ତା ନାହିଁ। ଆରମ୍ଭ କରିବାକୁ ଆଇନଗତ ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ।", signedIn: "ସାଇନ୍ ଇନ୍ ହୋଇଛି", logout: "ଲଗ୍ ଆଉଟ୍",
    disclaimer: "ଉତ୍ତରଗୁଡ଼ିକ ଆପଣଙ୍କ ପ୍ରକ୍ରିୟାକୃତ ଦଲିଲରୁ ମିଳିଥିବା ଆଇନଗତ ପାଠ୍ୟ ଉପରେ ଆଧାରିତ। ଔପଚାରିକ ବ୍ୟବହାର ପୂର୍ବରୁ ମୂଳ ଉତ୍ସ ଯାଞ୍ଚ କରନ୍ତୁ।", voice: "ସ୍ୱର", autoSpeak: "ଉତ୍ତର ପଢ଼ନ୍ତୁ", export: "↓ ରପ୍ତାନି", clear: "ସଫା କରନ୍ତୁ", downloadConversation: "କଥାବାର୍ତ୍ତାକୁ TXT ଭାବେ ଡାଉନଲୋଡ୍ କରନ୍ତୁ",
    welcomeTitle: "AI ନ୍ୟାୟିକ ଆଇନ ସହାୟକ", welcomeDescription: "ଭାରତୀୟ ଆଇନ, ଆଇନଗତ ଦଲିଲ କିମ୍ବା ଦୈନନ୍ଦିନ ବିଷୟ ବିଷୟରେ ପଚାରନ୍ତୁ।", p19Title: "ଧାରା 19: ମତପ୍ରକାଶର ସ୍ୱାଧୀନତା", p19Desc: "ଛଅଟି ସ୍ୱାଧୀନତା ଏବଂ ସେଗୁଡ଼ିକ ଉପରେ ସାମ୍ବିଧାନିକ ସୀମା", p14Title: "ଧାରା 14: ସମାନତାର ଅଧିକାର", p14Desc: "ଆଇନର ସମାନ ସୁରକ୍ଷା ଏବଂ ଭେଦଭାବ ନିଷେଧ",
    p21Title: "ଧାରା 21: ଜୀବନ ଓ ସ୍ୱାଧୀନତା", p21Desc: "ଜୀବନ, ସ୍ୱାଧୀନତା ଏବଂ ଗୋପନୀୟତାର ସୁରକ୍ଷା", p32Title: "ଧାରା 32: ସାମ୍ବିଧାନିକ ପ୍ରତିକାର", p32Desc: "ସୁପ୍ରିମକୋର୍ଟର ରିଟ୍ ଏବଂ ସାମ୍ବିଧାନିକ ପ୍ରତିକାର", pTamilTitle: "ଧାରା 19 ତାମିଲରେ", pTamilDesc: "ମତପ୍ରକାଶର ସ୍ୱାଧୀନତା ଏବଂ ଛଅଟି ମୌଳିକ ଅଧିକାର", pTeluguTitle: "ଧାରା 19 ତେଲୁଗୁରେ", pTeluguDesc: "ମତପ୍ରକାଶର ସ୍ୱାଧୀନତା ଏବଂ ଛଅଟି ମୌଳିକ ଅଧିକାର",
    nlpActive: "ବହୁଭାଷୀ ଆଇନ NLP ପ୍ରସ୍ତୁତ", editingPrevious: "ପୂର୍ବ ସନ୍ଦେଶ ସମ୍ପାଦନ ହେଉଛି। ପଠାଇଲେ ଏହା ପରର ସନ୍ଦେଶଗୁଡ଼ିକ ବଦଳିଯିବ।", cancel: "ବାତିଲ୍", stopRecording: "ରେକର୍ଡିଂ ବନ୍ଦ କରନ୍ତୁ", startRecording: "ରେକର୍ଡିଂ ଆରମ୍ଭ କରନ୍ତୁ", askByVoice: "ସ୍ୱରରେ ପଚାରନ୍ତୁ", inputPlaceholder: "ଆଇନ କିମ୍ବା ଅନ୍ୟ ଯେକୌଣସି ବିଷୟରେ ପଚାରନ୍ତୁ…", stopGenerating: "ଉତ୍ତର ତିଆରି ବନ୍ଦ କରନ୍ତୁ", send: "ପଠାନ୍ତୁ", generating: "ଉତ୍ତର ତିଆରି ହେଉଛି। ଏହାକୁ ବନ୍ଦ କରନ୍ତୁ କିମ୍ବା ସନ୍ଦେଶ ସମ୍ପାଦନ କରି ଅଟକାନ୍ତୁ।", recording: "ରେକର୍ଡିଂ… ବନ୍ଦ କରି ଲେଖାରେ ପରିଣତ କରିବାକୁ ମାଇକ୍ରୋଫୋନ୍ ପୁଣି ଦବାନ୍ତୁ।", copy: "⧉ କପି କରନ୍ତୁ", copied: "✓ କପି ହେଲା", responseTime: "ଉତ୍ତର ସମୟ", detectedIntent: "ଚିହ୍ନଟ ଉଦ୍ଦେଶ୍ୟ",
    editResend: "ସମ୍ପାଦନ କରି ପୁଣି ପଠାନ୍ତୁ", editMessage: "ସନ୍ଦେଶ ସମ୍ପାଦନ କରନ୍ତୁ", language: "ଭାଷା", hideSource: "ଉତ୍ସ ଲୁଚାନ୍ତୁ", viewSource: "ଉତ୍ସ ଦେଖନ୍ତୁ", exportConversation: "କଥାବାର୍ତ୍ତା ରପ୍ତାନି କରନ୍ତୁ", listen: "ଅଡିଓ ଶୁଣନ୍ତୁ", stopPlayback: "ଅଡିଓ ବନ୍ଦ କରନ୍ତୁ", replay: "ପୁଣି ଶୁଣନ୍ତୁ", relatedProvisions: "ସମ୍ବନ୍ଧିତ ବ୍ୟବସ୍ଥା", reference: "ସନ୍ଦର୍ଭ", article: "ଧାରା", section: "ଉପଧାରା", rule: "ନିୟମ",
    languageSelector: "ଡ୍ୟାସବୋର୍ଡ ଏବଂ ଉତ୍ତର ଭାଷା", manualOverride: "ଉତ୍ତର ଭାଷା: {language}", autoDetectTitle: "ପ୍ରତ୍ୟେକ ସନ୍ଦେଶର ଭାଷା ସ୍ୱୟଂଚାଳିତ ଚିହ୍ନଟ କରନ୍ତୁ", reset: "ସ୍ୱୟଂଚାଳିତ ଚିହ୍ନଟକୁ ଫେରନ୍ତୁ", signInTitle: "ଆପଣଙ୍କ ଖାତାରେ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ", username: "ବ୍ୟବହାରକାରୀ ନାମ", password: "ପାସୱାର୍ଡ", signingIn: "ସାଇନ୍ ଇନ୍ ହେଉଛି…", signIn: "ସାଇନ୍ ଇନ୍", noAccount: "ଖାତା ନାହିଁ କି?", register: "ପଞ୍ଜୀକରଣ କରନ୍ତୁ", createAccount: "ଆପଣଙ୍କ ଖାତା ତିଆରି କରନ୍ତୁ", privateHistory: "ଆପଣଙ୍କ କଥାବାର୍ତ୍ତା ଇତିହାସ ଆପଣଙ୍କ ଖାତାରେ ବ୍ୟକ୍ତିଗତ ରହିବ", emailOptional: "ଇମେଲ୍ (ଇଚ୍ଛାଧୀନ)", confirmPassword: "ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ", passwordMismatch: "ପାସୱାର୍ଡ ମେଳ ଖାଉନାହିଁ।", passwordMin: "ପାସୱାର୍ଡରେ ଅତି କମରେ 6ଟି ଅକ୍ଷର ଥିବା ଦରକାର।", creatingAccount: "ଖାତା ତିଆରି ହେଉଛି…", alreadyAccount: "ପୂର୍ବରୁ ଖାତା ଅଛି କି?", errorLoad: "କଥାବାର୍ତ୍ତା ଲୋଡ୍ ହୋଇପାରିଲା ନାହିଁ।", errorDelete: "କଥାବାର୍ତ୍ତା ହଟାଯାଇପାରିଲା ନାହିଁ।", errorUpdate: "ପୁଣି ପଠାଇବା ପୂର୍ବରୁ କଥାବାର୍ତ୍ତା ଅପଡେଟ୍ ହୋଇପାରିଲା ନାହିଁ।", errorEmptyExport: "ରପ୍ତାନି ପୂର୍ବରୁ ଏକ ସନ୍ଦେଶ ପଠାନ୍ତୁ।", errorExport: "କଥାବାର୍ତ୍ତା ରପ୍ତାନି ହୋଇପାରିଲା ନାହିଁ।", errorTranscribe: "ଅଡିଓକୁ ଲେଖାରେ ପରିଣତ କରାଯାଇପାରିଲା ନାହିଁ।",
  },
  Telugu: {
    loading: "లోడ్ అవుతోంది…", legalAssistant: "న్యాయ సహాయకుడు", newConversation: "కొత్త సంభాషణ", emptyConversations: "ఇంకా సంభాషణలు లేవు. ప్రారంభించడానికి న్యాయ ప్రశ్న అడగండి.", signedIn: "సైన్ ఇన్ అయ్యారు", logout: "లాగ్ అవుట్",
    disclaimer: "సమాధానాలు మీరు ప్రాసెస్ చేసిన పత్రాల నుంచి పొందిన న్యాయ పాఠ్యంపై ఆధారపడతాయి. అధికారిక వినియోగానికి ముందు అసలు మూలాన్ని ధృవీకరించండి.", voice: "వాయిస్", autoSpeak: "సమాధానం చదవండి", export: "↓ ఎగుమతి", clear: "తొలగించు", downloadConversation: "సంభాషణను TXTగా డౌన్‌లోడ్ చేయండి",
    welcomeTitle: "AI న్యాయ సహాయకుడు", welcomeDescription: "భారత చట్టం, న్యాయ పత్రాలు లేదా రోజువారీ విషయాల గురించి అడగండి.", p19Title: "ఆర్టికల్ 19: వాక్ స్వాతంత్ర్యం", p19Desc: "ఆరు స్వేచ్ఛలు మరియు వాటిపై రాజ్యాంగ పరిమితులు", p14Title: "ఆర్టికల్ 14: సమానత్వ హక్కు", p14Desc: "చట్టాల సమాన రక్షణ మరియు వివక్ష నిషేధం", p21Title: "ఆర్టికల్ 21: జీవితం మరియు స్వేచ్ఛ", p21Desc: "జీవితం, స్వేచ్ఛ మరియు గోప్యతకు రక్షణ", p32Title: "ఆర్టికల్ 32: రాజ్యాంగ పరిష్కారాలు", p32Desc: "సుప్రీంకోర్టు రిట్లు మరియు రాజ్యాంగ పరిష్కారాలు", pTamilTitle: "ఆర్టికల్ 19 తమిళంలో", pTamilDesc: "వాక్ స్వాతంత్ర్యం మరియు ఆరు ప్రాథమిక హక్కులు", pTeluguTitle: "ఆర్టికల్ 19 తెలుగులో", pTeluguDesc: "వాక్ స్వాతంత్ర్యం మరియు ఆరు ప్రాథమిక హక్కులు",
    nlpActive: "బహుభాషా న్యాయ NLP సిద్ధంగా ఉంది", editingPrevious: "మునుపటి సందేశాన్ని సవరిస్తున్నారు. పంపితే దాని తర్వాతి సందేశాలు మారతాయి.", cancel: "రద్దు", stopRecording: "రికార్డింగ్ ఆపు", startRecording: "రికార్డింగ్ ప్రారంభించు", askByVoice: "వాయిస్‌తో అడగండి", inputPlaceholder: "చట్టం లేదా మరే ఇతర విషయం గురించి అడగండి…", stopGenerating: "సమాధానం తయారీ ఆపు", send: "పంపు", generating: "సమాధానం తయారవుతోంది. ఆపవచ్చు లేదా సందేశాన్ని సవరించి మధ్యలో ఆపవచ్చు.", recording: "రికార్డింగ్… ఆపి వచనంగా మార్చడానికి మైక్‌ను మళ్లీ నొక్కండి.", copy: "⧉ కాపీ", copied: "✓ కాపీ అయింది", responseTime: "సమాధాన సమయం", detectedIntent: "గుర్తించిన ఉద్దేశం",
    editResend: "సవరించి మళ్లీ పంపు", editMessage: "సందేశాన్ని సవరించు", language: "భాష", hideSource: "మూలాన్ని దాచు", viewSource: "మూలాన్ని చూడు", exportConversation: "సంభాషణను ఎగుమతి చేయి", listen: "ఆడియో వినండి", stopPlayback: "ఆడియో ఆపు", replay: "మళ్లీ వినండి", relatedProvisions: "సంబంధిత నిబంధనలు", reference: "సూచన", article: "ఆర్టికల్", section: "సెక్షన్", rule: "నియమం",
    languageSelector: "డ్యాష్‌బోర్డ్ మరియు సమాధాన భాష", manualOverride: "సమాధాన భాష: {language}", autoDetectTitle: "ప్రతి సందేశ భాషను స్వయంచాలకంగా గుర్తించు", reset: "ఆటో-డిటెక్ట్‌కు తిరిగి వెళ్లు", signInTitle: "మీ ఖాతాలోకి సైన్ ఇన్ చేయండి", username: "వినియోగదారు పేరు", password: "పాస్‌వర్డ్", signingIn: "సైన్ ఇన్ అవుతోంది…", signIn: "సైన్ ఇన్", noAccount: "ఖాతా లేదా?", register: "నమోదు చేయండి", createAccount: "మీ ఖాతాను సృష్టించండి", privateHistory: "మీ సంభాషణ చరిత్ర మీ ఖాతాలో మాత్రమే ప్రైవేట్‌గా ఉంటుంది", emailOptional: "ఇమెయిల్ (ఐచ్ఛికం)", confirmPassword: "పాస్‌వర్డ్‌ను నిర్ధారించండి", passwordMismatch: "పాస్‌వర్డ్‌లు సరిపోలలేదు.", passwordMin: "పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి.", creatingAccount: "ఖాతా సృష్టిస్తోంది…", alreadyAccount: "ఇప్పటికే ఖాతా ఉందా?", errorLoad: "సంభాషణను లోడ్ చేయలేకపోయాం.", errorDelete: "సంభాషణను తొలగించలేకపోయాం.", errorUpdate: "మళ్లీ పంపే ముందు సంభాషణను నవీకరించలేకపోయాం.", errorEmptyExport: "ఎగుమతి చేయడానికి ముందు సందేశం పంపండి.", errorExport: "సంభాషణను ఎగుమతి చేయలేకపోయాం.", errorTranscribe: "ఆడియోను వచనంగా మార్చలేకపోయాం.",
  },
  Kannada: {
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ…", legalAssistant: "ಕಾನೂನು ಸಹಾಯಕ", newConversation: "ಹೊಸ ಸಂಭಾಷಣೆ", emptyConversations: "ಇನ್ನೂ ಸಂಭಾಷಣೆಗಳಿಲ್ಲ. ಪ್ರಾರಂಭಿಸಲು ಕಾನೂನು ಪ್ರಶ್ನೆ ಕೇಳಿ.", signedIn: "ಸೈನ್ ಇನ್ ಆಗಿದ್ದೀರಿ", logout: "ಲಾಗ್ ಔಟ್",
    disclaimer: "ಉತ್ತರಗಳು ನೀವು ಸಂಸ್ಕರಿಸಿದ ದಾಖಲೆಗಳಿಂದ ಪಡೆದ ಕಾನೂನು ಪಠ್ಯವನ್ನು ಆಧರಿಸಿವೆ. ಅಧಿಕೃತ ಬಳಕೆಗೆ ಮೊದಲು ಮೂಲವನ್ನು ಪರಿಶೀಲಿಸಿ.", voice: "ಧ್ವನಿ", autoSpeak: "ಉತ್ತರವನ್ನು ಓದಿ", export: "↓ ರಫ್ತು", clear: "ಅಳಿಸಿ", downloadConversation: "ಸಂಭಾಷಣೆಯನ್ನು TXT ಆಗಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    welcomeTitle: "AI ನ್ಯಾಯಾಂಗ ಕಾನೂನು ಸಹಾಯಕ", welcomeDescription: "ಭಾರತೀಯ ಕಾನೂನು, ಕಾನೂನು ದಾಖಲೆಗಳು ಅಥವಾ ದೈನಂದಿನ ವಿಷಯಗಳ ಬಗ್ಗೆ ಕೇಳಿ.", p19Title: "ವಿಧಿ 19: ಮಾತಿನ ಸ್ವಾತಂತ್ರ್ಯ", p19Desc: "ಆರು ಸ್ವಾತಂತ್ರ್ಯಗಳು ಮತ್ತು ಅವುಗಳ ಮೇಲಿನ ಸಾಂವಿಧಾನಿಕ ನಿರ್ಬಂಧಗಳು", p14Title: "ವಿಧಿ 14: ಸಮಾನತೆಯ ಹಕ್ಕು", p14Desc: "ಕಾನೂನಿನ ಸಮಾನ ರಕ್ಷಣೆ ಮತ್ತು ತಾರತಮ್ಯ ನಿಷೇಧ", p21Title: "ವಿಧಿ 21: ಜೀವನ ಮತ್ತು ಸ್ವಾತಂತ್ರ್ಯ", p21Desc: "ಜೀವನ, ಸ್ವಾತಂತ್ರ್ಯ ಮತ್ತು ಗೌಪ್ಯತೆಯ ರಕ್ಷಣೆ", p32Title: "ವಿಧಿ 32: ಸಾಂವಿಧಾನಿಕ ಪರಿಹಾರಗಳು", p32Desc: "ಸುಪ್ರೀಂ ಕೋರ್ಟ್ ರಿಟ್‌ಗಳು ಮತ್ತು ಸಾಂವಿಧಾನಿಕ ಪರಿಹಾರಗಳು", pTamilTitle: "ವಿಧಿ 19 ತಮಿಳಿನಲ್ಲಿ", pTamilDesc: "ಮಾತಿನ ಸ್ವಾತಂತ್ರ್ಯ ಮತ್ತು ಆರು ಮೂಲಭೂತ ಹಕ್ಕುಗಳು", pTeluguTitle: "ವಿಧಿ 19 ತೆಲುಗಿನಲ್ಲಿ", pTeluguDesc: "ಮಾತಿನ ಸ್ವಾತಂತ್ರ್ಯ ಮತ್ತು ಆರು ಮೂಲಭೂತ ಹಕ್ಕುಗಳು",
    nlpActive: "ಬಹುಭಾಷಾ ಕಾನೂನು NLP ಸಿದ್ಧವಾಗಿದೆ", editingPrevious: "ಹಿಂದಿನ ಸಂದೇಶವನ್ನು ಸಂಪಾದಿಸಲಾಗುತ್ತಿದೆ. ಕಳುಹಿಸಿದರೆ ಅದರ ನಂತರದ ಸಂದೇಶಗಳು ಬದಲಾಗುತ್ತವೆ.", cancel: "ರದ್ದುಮಾಡಿ", stopRecording: "ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ", startRecording: "ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ", askByVoice: "ಧ್ವನಿಯಲ್ಲಿ ಕೇಳಿ", inputPlaceholder: "ಕಾನೂನು ಅಥವಾ ಬೇರೆ ಯಾವುದೇ ವಿಷಯದ ಬಗ್ಗೆ ಕೇಳಿ…", stopGenerating: "ಉತ್ತರ ರಚಿಸುವುದನ್ನು ನಿಲ್ಲಿಸಿ", send: "ಕಳುಹಿಸಿ", generating: "ಉತ್ತರ ಸಿದ್ಧವಾಗುತ್ತಿದೆ. ನಿಲ್ಲಿಸಬಹುದು ಅಥವಾ ಸಂದೇಶ ಸಂಪಾದಿಸಿ ಮಧ್ಯೆ ನಿಲ್ಲಿಸಬಹುದು.", recording: "ರೆಕಾರ್ಡಿಂಗ್… ನಿಲ್ಲಿಸಿ ಪಠ್ಯಕ್ಕೆ ಪರಿವರ್ತಿಸಲು ಮೈಕ್ ಅನ್ನು ಮತ್ತೆ ಒತ್ತಿ.", copy: "⧉ ನಕಲಿಸಿ", copied: "✓ ನಕಲಿಸಲಾಗಿದೆ", responseTime: "ಉತ್ತರದ ಸಮಯ", detectedIntent: "ಗುರುತಿಸಿದ ಉದ್ದೇಶ",
    editResend: "ಸಂಪಾದಿಸಿ ಮತ್ತೆ ಕಳುಹಿಸಿ", editMessage: "ಸಂದೇಶ ಸಂಪಾದಿಸಿ", language: "ಭಾಷೆ", hideSource: "ಮೂಲವನ್ನು ಮರೆಮಾಡಿ", viewSource: "ಮೂಲವನ್ನು ನೋಡಿ", exportConversation: "ಸಂಭಾಷಣೆಯನ್ನು ರಫ್ತು ಮಾಡಿ", listen: "ಆಡಿಯೊ ಕೇಳಿ", stopPlayback: "ಆಡಿಯೊ ನಿಲ್ಲಿಸಿ", replay: "ಮತ್ತೆ ಕೇಳಿ", relatedProvisions: "ಸಂಬಂಧಿತ ನಿಯಮಗಳು", reference: "ಉಲ್ಲೇಖ", article: "ವಿಧಿ", section: "ವಿಭಾಗ", rule: "ನಿಯಮ",
    languageSelector: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಮತ್ತು ಉತ್ತರದ ಭಾಷೆ", manualOverride: "ಉತ್ತರದ ಭಾಷೆ: {language}", autoDetectTitle: "ಪ್ರತಿ ಸಂದೇಶದ ಭಾಷೆಯನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಗುರುತಿಸಿ", reset: "ಸ್ವಯಂ ಪತ್ತೆಗೆ ಹಿಂತಿರುಗಿ", signInTitle: "ನಿಮ್ಮ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ", username: "ಬಳಕೆದಾರ ಹೆಸರು", password: "ಪಾಸ್‌ವರ್ಡ್", signingIn: "ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ…", signIn: "ಸೈನ್ ಇನ್", noAccount: "ಖಾತೆ ಇಲ್ಲವೇ?", register: "ನೋಂದಣಿ ಮಾಡಿ", createAccount: "ನಿಮ್ಮ ಖಾತೆ ರಚಿಸಿ", privateHistory: "ನಿಮ್ಮ ಸಂಭಾಷಣೆ ಇತಿಹಾಸ ನಿಮ್ಮ ಖಾತೆಗೆ ಮಾತ್ರ ಖಾಸಗಿಯಾಗಿರುತ್ತದೆ", emailOptional: "ಇಮೇಲ್ (ಐಚ್ಛಿಕ)", confirmPassword: "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ", passwordMismatch: "ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ.", passwordMin: "ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಿರಬೇಕು.", creatingAccount: "ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ…", alreadyAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?", errorLoad: "ಸಂಭಾಷಣೆಯನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.", errorDelete: "ಸಂಭಾಷಣೆಯನ್ನು ಅಳಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.", errorUpdate: "ಮತ್ತೆ ಕಳುಹಿಸುವ ಮೊದಲು ಸಂಭಾಷಣೆಯನ್ನು ನವೀಕರಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.", errorEmptyExport: "ರಫ್ತು ಮಾಡುವ ಮೊದಲು ಸಂದೇಶ ಕಳುಹಿಸಿ.", errorExport: "ಸಂಭಾಷಣೆಯನ್ನು ರಫ್ತು ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.", errorTranscribe: "ಆಡಿಯೊವನ್ನು ಪಠ್ಯಕ್ಕೆ ಪರಿವರ್ತಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
  },
  Malayalam: {
    loading: "ലോഡ് ചെയ്യുന്നു…", legalAssistant: "നിയമ സഹായി", newConversation: "പുതിയ സംഭാഷണം", emptyConversations: "ഇതുവരെ സംഭാഷണങ്ങളില്ല. തുടങ്ങാൻ നിയമപരമായ ചോദ്യം ചോദിക്കൂ.", signedIn: "സൈൻ ഇൻ ചെയ്തു", logout: "ലോഗ് ഔട്ട്",
    disclaimer: "നിങ്ങൾ പ്രോസസ്സ് ചെയ്ത രേഖകളിൽ നിന്ന് ലഭിച്ച നിയമവിവരങ്ങളെ അടിസ്ഥാനമാക്കിയാണ് ഉത്തരങ്ങൾ. ഔദ്യോഗിക ആവശ്യങ്ങൾക്ക് മുമ്പ് യഥാർത്ഥ ഉറവിടം പരിശോധിക്കുക.", voice: "ശബ്ദം", autoSpeak: "ഉത്തരം വായിക്കുക", export: "↓ കയറ്റുമതി", clear: "മായ്ക്കുക", downloadConversation: "സംഭാഷണം TXT ആയി ഡൗൺലോഡ് ചെയ്യുക",
    welcomeTitle: "AI ജുഡീഷ്യറി നിയമ സഹായി", welcomeDescription: "ഇന്ത്യൻ നിയമം, നിയമരേഖകൾ, അല്ലെങ്കിൽ ദൈനംദിന വിഷയങ്ങൾ ചോദിക്കൂ.", p19Title: "ആർട്ടിക്കിൾ 19: അഭിപ്രായ സ്വാതന്ത്ര്യം", p19Desc: "ആറ് സ്വാതന്ത്ര്യങ്ങളും അവയ്ക്കുള്ള ഭരണഘടനാപരമായ നിയന്ത്രണങ്ങളും", p14Title: "ആർട്ടിക്കിൾ 14: സമത്വത്തിനുള്ള അവകാശം", p14Desc: "നിയമത്തിന്റെ തുല്യ സംരക്ഷണവും വിവേചന നിരോധനവും", p21Title: "ആർട്ടിക്കിൾ 21: ജീവനും സ്വാതന്ത്ര്യവും", p21Desc: "ജീവൻ, സ്വാതന്ത്ര്യം, സ്വകാര്യത എന്നിവയുടെ സംരക്ഷണം", p32Title: "ആർട്ടിക്കിൾ 32: ഭരണഘടനാപരമായ പരിഹാരങ്ങൾ", p32Desc: "സുപ്രീം കോടതി റിട്ടുകളും ഭരണഘടനാപരമായ പരിഹാരങ്ങളും", pTamilTitle: "ആർട്ടിക്കിൾ 19 തമിഴിൽ", pTamilDesc: "അഭിപ്രായ സ്വാതന്ത്ര്യവും ആറ് മൗലികാവകാശങ്ങളും", pTeluguTitle: "ആർട്ടിക്കിൾ 19 തെലുങ്കിൽ", pTeluguDesc: "അഭിപ്രായ സ്വാതന്ത്ര്യവും ആറ് മൗലികാവകാശങ്ങളും",
    nlpActive: "ബഹുഭാഷാ നിയമ NLP തയ്യാറാണ്", editingPrevious: "മുമ്പത്തെ സന്ദേശം തിരുത്തുന്നു. അയച്ചാൽ അതിനു ശേഷമുള്ള സന്ദേശങ്ങൾ മാറ്റപ്പെടും.", cancel: "റദ്ദാക്കുക", stopRecording: "റെക്കോർഡിംഗ് നിർത്തുക", startRecording: "റെക്കോർഡിംഗ് ആരംഭിക്കുക", askByVoice: "ശബ്ദത്തിൽ ചോദിക്കുക", inputPlaceholder: "നിയമത്തെക്കുറിച്ചോ മറ്റേതെങ്കിലും വിഷയത്തെക്കുറിച്ചോ ചോദിക്കൂ…", stopGenerating: "ഉത്തരം തയ്യാറാക്കുന്നത് നിർത്തുക", send: "അയയ്ക്കുക", generating: "ഉത്തരം തയ്യാറാക്കുന്നു. നിർത്തുകയോ സന്ദേശം തിരുത്തി ഇടയ്ക്ക് നിർത്തുകയോ ചെയ്യാം.", recording: "റെക്കോർഡിംഗ്… നിർത്തി എഴുത്താക്കാൻ മൈക്ക് വീണ്ടും അമർത്തുക.", copy: "⧉ പകർത്തുക", copied: "✓ പകർത്തി", responseTime: "ഉത്തര സമയം", detectedIntent: "കണ്ടെത്തിയ ഉദ്ദേശ്യം",
    editResend: "തിരുത്തി വീണ്ടും അയയ്ക്കുക", editMessage: "സന്ദേശം തിരുത്തുക", language: "ഭാഷ", hideSource: "ഉറവിടം മറയ്ക്കുക", viewSource: "ഉറവിടം കാണുക", exportConversation: "സംഭാഷണം കയറ്റുമതി ചെയ്യുക", listen: "ഓഡിയോ കേൾക്കുക", stopPlayback: "ഓഡിയോ നിർത്തുക", replay: "വീണ്ടും കേൾക്കുക", relatedProvisions: "ബന്ധപ്പെട്ട വ്യവസ്ഥകൾ", reference: "റഫറൻസ്", article: "ആർട്ടിക്കിൾ", section: "വകുപ്പ്", rule: "ചട്ടം",
    languageSelector: "ഡാഷ്ബോർഡിന്റെയും ഉത്തരത്തിന്റെയും ഭാഷ", manualOverride: "ഉത്തര ഭാഷ: {language}", autoDetectTitle: "ഓരോ സന്ദേശത്തിന്റെയും ഭാഷ സ്വയം കണ്ടെത്തുക", reset: "സ്വയം കണ്ടെത്തലിലേക്ക് മടങ്ങുക", signInTitle: "നിങ്ങളുടെ അക്കൗണ്ടിൽ സൈൻ ഇൻ ചെയ്യുക", username: "ഉപയോക്തൃനാമം", password: "പാസ്‌വേഡ്", signingIn: "സൈൻ ഇൻ ചെയ്യുന്നു…", signIn: "സൈൻ ഇൻ", noAccount: "അക്കൗണ്ട് ഇല്ലേ?", register: "രജിസ്റ്റർ ചെയ്യുക", createAccount: "നിങ്ങളുടെ അക്കൗണ്ട് സൃഷ്ടിക്കുക", privateHistory: "നിങ്ങളുടെ സംഭാഷണ ചരിത്രം നിങ്ങളുടെ അക്കൗണ്ടിൽ മാത്രം സ്വകാര്യമാണ്", emailOptional: "ഇമെയിൽ (ഐച്ഛികം)", confirmPassword: "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക", passwordMismatch: "പാസ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല.", passwordMin: "പാസ്‌വേഡിന് കുറഞ്ഞത് 6 അക്ഷരങ്ങൾ വേണം.", creatingAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുന്നു…", alreadyAccount: "ഇതിനകം അക്കൗണ്ടുണ്ടോ?", errorLoad: "സംഭാഷണം ലോഡ് ചെയ്യാനായില്ല.", errorDelete: "സംഭാഷണം ഇല്ലാതാക്കാനായില്ല.", errorUpdate: "വീണ്ടും അയയ്ക്കുന്നതിന് മുമ്പ് സംഭാഷണം പുതുക്കാനായില്ല.", errorEmptyExport: "കയറ്റുമതി ചെയ്യുന്നതിന് മുമ്പ് സന്ദേശം അയയ്ക്കുക.", errorExport: "സംഭാഷണം കയറ്റുമതി ചെയ്യാനായില്ല.", errorTranscribe: "ഓഡിയോ എഴുത്താക്കി മാറ്റാനായില്ല.",
  },
  Bengali: {
    loading: "লোড হচ্ছে…", legalAssistant: "আইনি সহায়ক", newConversation: "নতুন কথোপকথন", emptyConversations: "এখনও কোনো কথোপকথন নেই। শুরু করতে আইনি প্রশ্ন করুন।", signedIn: "সাইন ইন করা হয়েছে", logout: "লগ আউট",
    disclaimer: "উত্তরগুলি আপনার প্রক্রিয়াকৃত নথি থেকে পাওয়া আইনি পাঠ্যের ভিত্তিতে তৈরি। আনুষ্ঠানিক ব্যবহারের আগে মূল উৎস যাচাই করুন।", voice: "ভয়েস", autoSpeak: "উত্তর পড়ে শোনান", export: "↓ রপ্তানি", clear: "মুছুন", downloadConversation: "কথোপকথন TXT হিসেবে ডাউনলোড করুন",
    welcomeTitle: "AI বিচার বিভাগীয় আইনি সহায়ক", welcomeDescription: "ভারতীয় আইন, আইনি নথি বা দৈনন্দিন বিষয় সম্পর্কে জিজ্ঞাসা করুন।", p19Title: "অনুচ্ছেদ 19: বাক্‌স্বাধীনতা", p19Desc: "ছয়টি স্বাধীনতা ও সেগুলির সাংবিধানিক সীমাবদ্ধতা", p14Title: "অনুচ্ছেদ 14: সমতার অধিকার", p14Desc: "আইনের সমান সুরক্ষা ও বৈষম্য নিষিদ্ধকরণ", p21Title: "অনুচ্ছেদ 21: জীবন ও স্বাধীনতা", p21Desc: "জীবন, স্বাধীনতা ও গোপনীয়তার সুরক্ষা", p32Title: "অনুচ্ছেদ 32: সাংবিধানিক প্রতিকার", p32Desc: "সুপ্রিম কোর্টের রিট ও সাংবিধানিক প্রতিকার", pTamilTitle: "তামিলে অনুচ্ছেদ 19", pTamilDesc: "বাক্‌স্বাধীনতা ও ছয়টি মৌলিক অধিকার", pTeluguTitle: "তেলুগুতে অনুচ্ছেদ 19", pTeluguDesc: "বাক্‌স্বাধীনতা ও ছয়টি মৌলিক অধিকার",
    nlpActive: "বহুভাষিক আইনি NLP প্রস্তুত", editingPrevious: "আগের বার্তাটি সম্পাদনা হচ্ছে। পাঠালে এর পরের বার্তাগুলি বদলে যাবে।", cancel: "বাতিল", stopRecording: "রেকর্ডিং বন্ধ করুন", startRecording: "রেকর্ডিং শুরু করুন", askByVoice: "কণ্ঠে জিজ্ঞাসা করুন", inputPlaceholder: "আইন বা অন্য যেকোনো বিষয় সম্পর্কে প্রশ্ন করুন…", stopGenerating: "উত্তর তৈরি বন্ধ করুন", send: "পাঠান", generating: "উত্তর তৈরি হচ্ছে। থামাতে পারেন, অথবা বার্তা সম্পাদনা করে মাঝপথে থামাতে পারেন।", recording: "রেকর্ড হচ্ছে… থামিয়ে লেখায় রূপান্তর করতে মাইক্রোফোনে আবার চাপুন।", copy: "⧉ কপি করুন", copied: "✓ কপি হয়েছে", responseTime: "উত্তরের সময়", detectedIntent: "শনাক্ত উদ্দেশ্য",
    editResend: "সম্পাদনা করে আবার পাঠান", editMessage: "বার্তা সম্পাদনা করুন", language: "ভাষা", hideSource: "উৎস লুকান", viewSource: "উৎস দেখুন", exportConversation: "কথোপকথন রপ্তানি করুন", listen: "অডিও শুনুন", stopPlayback: "অডিও থামান", replay: "আবার শুনুন", relatedProvisions: "সম্পর্কিত বিধান", reference: "তথ্যসূত্র", article: "অনুচ্ছেদ", section: "ধারা", rule: "নিয়ম",
    languageSelector: "ড্যাশবোর্ড ও উত্তরের ভাষা", manualOverride: "উত্তরের ভাষা: {language}", autoDetectTitle: "প্রতিটি বার্তার ভাষা স্বয়ংক্রিয়ভাবে শনাক্ত করুন", reset: "স্বয়ংক্রিয় শনাক্তকরণে ফিরুন", signInTitle: "আপনার অ্যাকাউন্টে সাইন ইন করুন", username: "ব্যবহারকারীর নাম", password: "পাসওয়ার্ড", signingIn: "সাইন ইন হচ্ছে…", signIn: "সাইন ইন", noAccount: "অ্যাকাউন্ট নেই?", register: "নিবন্ধন করুন", createAccount: "আপনার অ্যাকাউন্ট তৈরি করুন", privateHistory: "আপনার কথোপকথনের ইতিহাস শুধু আপনার অ্যাকাউন্টেই ব্যক্তিগত থাকে", emailOptional: "ইমেল (ঐচ্ছিক)", confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন", passwordMismatch: "পাসওয়ার্ড মিলছে না।", passwordMin: "পাসওয়ার্ডে অন্তত 6টি অক্ষর থাকতে হবে।", creatingAccount: "অ্যাকাউন্ট তৈরি হচ্ছে…", alreadyAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?", errorLoad: "কথোপকথন লোড করা যায়নি।", errorDelete: "কথোপকথন মুছে ফেলা যায়নি।", errorUpdate: "আবার পাঠানোর আগে কথোপকথন আপডেট করা যায়নি।", errorEmptyExport: "রপ্তানির আগে একটি বার্তা পাঠান।", errorExport: "কথোপকথন রপ্তানি করা যায়নি।", errorTranscribe: "অডিওকে লেখায় রূপান্তর করা যায়নি।",
  },
  Marathi: {
    loading: "लोड होत आहे…", legalAssistant: "कायदेशीर सहाय्यक", newConversation: "नवीन संभाषण", emptyConversations: "अद्याप संभाषण नाही. सुरुवात करण्यासाठी कायदेशीर प्रश्न विचारा.", signedIn: "साइन इन केले आहे", logout: "लॉग आउट",
    disclaimer: "उत्तरे तुमच्या प्रक्रिया केलेल्या दस्तऐवजांतून मिळालेल्या कायदेशीर मजकुरावर आधारित आहेत. औपचारिक वापरापूर्वी मूळ स्रोत तपासा.", voice: "आवाज", autoSpeak: "उत्तर वाचा", export: "↓ निर्यात", clear: "पुसून टाका", downloadConversation: "संभाषण TXT म्हणून डाउनलोड करा",
    welcomeTitle: "AI न्यायिक कायदेशीर सहाय्यक", welcomeDescription: "भारतीय कायदा, कायदेशीर दस्तऐवज किंवा दैनंदिन विषयांबद्दल विचारा.", p19Title: "अनुच्छेद 19: अभिव्यक्ती स्वातंत्र्य", p19Desc: "सहा स्वातंत्र्ये आणि त्यांवरील घटनात्मक मर्यादा", p14Title: "अनुच्छेद 14: समानतेचा अधिकार", p14Desc: "कायद्याचे समान संरक्षण आणि भेदभावास मनाई", p21Title: "अनुच्छेद 21: जीवन आणि स्वातंत्र्य", p21Desc: "जीवन, स्वातंत्र्य आणि गोपनीयतेचे संरक्षण", p32Title: "अनुच्छेद 32: घटनात्मक उपाय", p32Desc: "सर्वोच्च न्यायालयाचे रिट आणि घटनात्मक उपाय", pTamilTitle: "अनुच्छेद 19 तमिळमध्ये", pTamilDesc: "अभिव्यक्ती स्वातंत्र्य आणि सहा मूलभूत हक्क", pTeluguTitle: "अनुच्छेद 19 तेलुगूमध्ये", pTeluguDesc: "अभिव्यक्ती स्वातंत्र्य आणि सहा मूलभूत हक्क",
    nlpActive: "बहुभाषिक कायदेशीर NLP तयार आहे", editingPrevious: "मागील संदेश संपादित होत आहे. पाठवल्यावर त्यानंतरचे संदेश बदलतील.", cancel: "रद्द करा", stopRecording: "रेकॉर्डिंग थांबवा", startRecording: "रेकॉर्डिंग सुरू करा", askByVoice: "आवाजाने विचारा", inputPlaceholder: "कायदा किंवा इतर कोणत्याही विषयाबद्दल विचारा…", stopGenerating: "उत्तर तयार करणे थांबवा", send: "पाठवा", generating: "उत्तर तयार होत आहे. थांबवू शकता किंवा संदेश संपादित करून मध्येच थांबवू शकता.", recording: "रेकॉर्डिंग… थांबवून मजकूर मिळवण्यासाठी मायक्रोफोन पुन्हा दाबा.", copy: "⧉ प्रत करा", copied: "✓ प्रत केली", responseTime: "उत्तराचा वेळ", detectedIntent: "ओळखलेला हेतू",
    editResend: "संपादित करून पुन्हा पाठवा", editMessage: "संदेश संपादित करा", language: "भाषा", hideSource: "स्रोत लपवा", viewSource: "स्रोत पहा", exportConversation: "संभाषण निर्यात करा", listen: "ऑडिओ ऐका", stopPlayback: "ऑडिओ थांबवा", replay: "पुन्हा ऐका", relatedProvisions: "संबंधित तरतुदी", reference: "संदर्भ", article: "अनुच्छेद", section: "कलम", rule: "नियम",
    languageSelector: "डॅशबोर्ड आणि उत्तराची भाषा", manualOverride: "उत्तराची भाषा: {language}", autoDetectTitle: "प्रत्येक संदेशाची भाषा आपोआप ओळखा", reset: "स्वयं-ओळखीवर परत जा", signInTitle: "तुमच्या खात्यात साइन इन करा", username: "वापरकर्तानाव", password: "पासवर्ड", signingIn: "साइन इन होत आहे…", signIn: "साइन इन", noAccount: "खाते नाही?", register: "नोंदणी करा", createAccount: "तुमचे खाते तयार करा", privateHistory: "तुमचा संभाषण इतिहास तुमच्या खात्यात खाजगी राहतो", emailOptional: "ईमेल (ऐच्छिक)", confirmPassword: "पासवर्डची पुष्टी करा", passwordMismatch: "पासवर्ड जुळत नाहीत.", passwordMin: "पासवर्ड किमान 6 अक्षरांचा असावा.", creatingAccount: "खाते तयार होत आहे…", alreadyAccount: "आधीच खाते आहे?", errorLoad: "संभाषण लोड करता आले नाही.", errorDelete: "संभाषण हटवता आले नाही.", errorUpdate: "पुन्हा पाठवण्यापूर्वी संभाषण अद्ययावत करता आले नाही.", errorEmptyExport: "निर्यात करण्यापूर्वी संदेश पाठवा.", errorExport: "संभाषण निर्यात करता आले नाही.", errorTranscribe: "ऑडिओचे मजकुरात रूपांतर करता आले नाही.",
  },
  Gujarati: {
    loading: "લોડ થઈ રહ્યું છે…", legalAssistant: "કાનૂની સહાયક", newConversation: "નવી વાતચીત", emptyConversations: "હજુ સુધી કોઈ વાતચીત નથી. શરૂઆત કરવા કાનૂની પ્રશ્ન પૂછો.", signedIn: "સાઇન ઇન કર્યું છે", logout: "લૉગ આઉટ",
    disclaimer: "જવાબો તમારા પ્રોસેસ કરેલા દસ્તાવેજોમાંથી મેળવેલા કાનૂની લખાણ પર આધારિત છે. સત્તાવાર ઉપયોગ પહેલાં મૂળ સ્રોત તપાસો.", voice: "અવાજ", autoSpeak: "જવાબ બોલો", export: "↓ નિકાસ", clear: "સાફ કરો", downloadConversation: "વાતચીત TXT તરીકે ડાઉનલોડ કરો",
    welcomeTitle: "AI ન્યાયિક કાનૂની સહાયક", welcomeDescription: "ભારતીય કાયદા, કાનૂની દસ્તાવેજો અથવા રોજિંદા વિષયો વિશે પૂછો.", p19Title: "કલમ 19: વાણીની સ્વતંત્રતા", p19Desc: "છ સ્વતંત્રતાઓ અને તેમના પરની બંધારણીય મર્યાદાઓ", p14Title: "કલમ 14: સમાનતાનો અધિકાર", p14Desc: "કાયદાનું સમાન રક્ષણ અને ભેદભાવ પર પ્રતિબંધ", p21Title: "કલમ 21: જીવન અને સ્વતંત્રતા", p21Desc: "જીવન, સ્વતંત્રતા અને ગોપનીયતાનું રક્ષણ", p32Title: "કલમ 32: બંધારણીય ઉપાયો", p32Desc: "સર્વોચ્ચ અદાલતની રિટ અને બંધારણીય ઉપાયો", pTamilTitle: "કલમ 19 તમિલમાં", pTamilDesc: "વાણીની સ્વતંત્રતા અને છ મૂળભૂત અધિકારો", pTeluguTitle: "કલમ 19 તેલુગુમાં", pTeluguDesc: "વાણીની સ્વતંત્રતા અને છ મૂળભૂત અધિકારો",
    nlpActive: "બહુભાષી કાનૂની NLP તૈયાર છે", editingPrevious: "પહેલો સંદેશ સંપાદિત થઈ રહ્યો છે. મોકલવાથી તેના પછીના સંદેશા બદલાશે.", cancel: "રદ કરો", stopRecording: "રેકોર્ડિંગ બંધ કરો", startRecording: "રેકોર્ડિંગ શરૂ કરો", askByVoice: "અવાજથી પૂછો", inputPlaceholder: "કાયદા અથવા અન્ય કોઈપણ વિષય વિશે પૂછો…", stopGenerating: "જવાબ બનાવવાનું બંધ કરો", send: "મોકલો", generating: "જવાબ તૈયાર થઈ રહ્યો છે. તેને રોકી શકો અથવા સંદેશ સંપાદિત કરીને વચ્ચે રોકી શકો.", recording: "રેકોર્ડિંગ… રોકવા અને લખાણ મેળવવા માઇક્રોફોન ફરી દબાવો.", copy: "⧉ નકલ કરો", copied: "✓ નકલ થઈ", responseTime: "જવાબનો સમય", detectedIntent: "ઓળખાયેલ હેતુ",
    editResend: "સંપાદિત કરીને ફરી મોકલો", editMessage: "સંદેશ સંપાદિત કરો", language: "ભાષા", hideSource: "સ્રોત છુપાવો", viewSource: "સ્રોત જુઓ", exportConversation: "વાતચીત નિકાસ કરો", listen: "ઑડિયો સાંભળો", stopPlayback: "ઑડિયો બંધ કરો", replay: "ફરી સાંભળો", relatedProvisions: "સંબંધિત જોગવાઈઓ", reference: "સંદર્ભ", article: "કલમ", section: "વિભાગ", rule: "નિયમ",
    languageSelector: "ડૅશબોર્ડ અને જવાબની ભાષા", manualOverride: "જવાબની ભાષા: {language}", autoDetectTitle: "દરેક સંદેશની ભાષા આપમેળે ઓળખો", reset: "ઑટો-ડિટેક્ટ પર પાછા જાઓ", signInTitle: "તમારા ખાતામાં સાઇન ઇન કરો", username: "વપરાશકર્તા નામ", password: "પાસવર્ડ", signingIn: "સાઇન ઇન થઈ રહ્યું છે…", signIn: "સાઇન ઇન", noAccount: "ખાતું નથી?", register: "નોંધણી કરો", createAccount: "તમારું ખાતું બનાવો", privateHistory: "તમારી વાતચીતનો ઇતિહાસ તમારા ખાતામાં ખાનગી રહે છે", emailOptional: "ઈમેલ (વૈકલ્પિક)", confirmPassword: "પાસવર્ડની પુષ્ટિ કરો", passwordMismatch: "પાસવર્ડ મેળ ખાતા નથી.", passwordMin: "પાસવર્ડ ઓછામાં ઓછા 6 અક્ષરનો હોવો જોઈએ.", creatingAccount: "ખાતું બની રહ્યું છે…", alreadyAccount: "પહેલેથી ખાતું છે?", errorLoad: "વાતચીત લોડ થઈ શકી નથી.", errorDelete: "વાતચીત કાઢી શકાઈ નથી.", errorUpdate: "ફરી મોકલતા પહેલાં વાતચીત અપડેટ થઈ શકી નથી.", errorEmptyExport: "નિકાસ કરતાં પહેલાં સંદેશ મોકલો.", errorExport: "વાતચીત નિકાસ થઈ શકી નથી.", errorTranscribe: "ઑડિયોને લખાણમાં ફેરવી શકાયું નથી.",
  },
};

const EXTRA_COPY = {
  autoDetect: { English: "Auto-Detect", Hindi: "स्वचालित", Tamil: "தானியங்கு", Urdu: "خودکار", Punjabi: "ਆਟੋ-ਡਿਟੈਕਟ", Odia: "ସ୍ୱୟଂଚାଳିତ", Telugu: "ఆటో-డిటెక్ట్", Kannada: "ಸ್ವಯಂ ಪತ್ತೆ", Malayalam: "സ്വയം കണ്ടെത്തൽ", Bengali: "স্বয়ংক্রিয়", Marathi: "स्वयं-ओळख", Gujarati: "ઑટો-ડિટેક્ટ" },
  genericError: { English: "Something went wrong. Please try again.", Hindi: "कुछ गड़बड़ हुई। कृपया फिर से कोशिश करें।", Tamil: "ஏதோ தவறு ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.", Urdu: "کچھ غلط ہو گیا۔ دوبارہ کوشش کریں۔", Punjabi: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।", Odia: "କିଛି ତ୍ରୁଟି ହୋଇଛି। ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।", Telugu: "ఏదో తప్పు జరిగింది. దయచేసి మళ్లీ ప్రయత్నించండి.", Kannada: "ಏನೋ ತಪ್ಪಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", Malayalam: "എന്തോ പിഴവുണ്ടായി. വീണ്ടും ശ്രമിക്കൂ.", Bengali: "কিছু একটা সমস্যা হয়েছে। আবার চেষ্টা করুন।", Marathi: "काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा.", Gujarati: "કંઈક ખોટું થયું. કૃપા કરીને ફરી પ્રયાસ કરો." },
  translatingInto: { English: "Translating into {language}…", Hindi: "{language} में अनुवाद हो रहा है…", Tamil: "{language} மொழிக்கு மொழிபெயர்க்கப்படுகிறது…", Urdu: "{language} میں ترجمہ ہو رہا ہے…", Punjabi: "{language} ਵਿੱਚ ਅਨੁਵਾਦ ਹੋ ਰਿਹਾ ਹੈ…", Odia: "{language}କୁ ଅନୁବାଦ ହେଉଛି…", Telugu: "{language}లోకి అనువదిస్తోంది…", Kannada: "{language}ಗೆ ಅನುವಾದಿಸಲಾಗುತ್ತಿದೆ…", Malayalam: "{language}ലേക്ക് വിവർത്തനം ചെയ്യുന്നു…", Bengali: "{language}-এ অনুবাদ করা হচ্ছে…", Marathi: "{language} मध्ये भाषांतर होत आहे…", Gujarati: "{language}માં અનુવાદ થઈ રહ્યો છે…" },
  ttsUnsupported: { English: "This browser does not support text-to-speech.", Hindi: "यह ब्राउज़र टेक्स्ट-टू-स्पीच का समर्थन नहीं करता।", Tamil: "இந்த உலாவியில் உரையைப் பேச்சாக மாற்றும் வசதி இல்லை.", Urdu: "یہ براؤزر متن کو آواز میں تبدیل کرنے کی سہولت نہیں دیتا۔", Punjabi: "ਇਹ ਬ੍ਰਾਊਜ਼ਰ ਲਿਖਤ ਨੂੰ ਬੋਲਣ ਦੀ ਸਹੂਲਤ ਦਾ ਸਮਰਥਨ ਨਹੀਂ ਕਰਦਾ।", Odia: "ଏହି ବ୍ରାଉଜର୍‌ରେ ଟେକ୍ସଟ୍-ଟୁ-ସ୍ପିଚ୍ ସୁବିଧା ନାହିଁ।", Telugu: "ఈ బ్రౌజర్ టెక్స్ట్-టు-స్పీచ్‌కు మద్దతు ఇవ్వదు.", Kannada: "ಈ ಬ್ರೌಸರ್ ಪಠ್ಯದಿಂದ ಧ್ವನಿಗೆ ಪರಿವರ್ತನೆಯನ್ನು ಬೆಂಬಲಿಸುವುದಿಲ್ಲ.", Malayalam: "ഈ ബ്രൗസർ ടെക്സ്റ്റ്-ടു-സ്പീച്ച് പിന്തുണയ്ക്കുന്നില്ല.", Bengali: "এই ব্রাউজারে টেক্সট-টু-স্পিচ সুবিধা নেই।", Marathi: "हा ब्राउझर मजकूर-वाचन सुविधेला समर्थन देत नाही.", Gujarati: "આ બ્રાઉઝર લખાણને અવાજમાં ફેરવવાની સુવિધાને સમર્થન આપતું નથી." },
  conversation: { English: "Conversation", Hindi: "बातचीत", Tamil: "உரையாடல்", Urdu: "گفتگو", Punjabi: "ਗੱਲਬਾਤ", Odia: "କଥାବାର୍ତ୍ତା", Telugu: "సంభాషణ", Kannada: "ಸಂಭಾಷಣೆ", Malayalam: "സംഭാഷണം", Bengali: "কথোপকথন", Marathi: "संभाषण", Gujarati: "વાતચીત" },
  loginError: { English: "Could not log in. Check your details and try again.", Hindi: "साइन इन नहीं हो सका। जानकारी जाँचकर फिर कोशिश करें।", Tamil: "உள்நுழைய முடியவில்லை. விவரங்களைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.", Urdu: "سائن اِن نہیں ہو سکا۔ اپنی معلومات دیکھ کر دوبارہ کوشش کریں۔", Punjabi: "ਸਾਈਨ ਇਨ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਜਾਣਕਾਰੀ ਜਾਂਚ ਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।", Odia: "ସାଇନ୍ ଇନ୍ ହୋଇପାରିଲା ନାହିଁ। ବିବରଣୀ ଯାଞ୍ଚ କରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।", Telugu: "సైన్ ఇన్ కాలేదు. వివరాలు తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.", Kannada: "ಸೈನ್ ಇನ್ ಆಗಲಿಲ್ಲ. ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", Malayalam: "സൈൻ ഇൻ ചെയ്യാനായില്ല. വിവരങ്ങൾ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കൂ.", Bengali: "সাইন ইন করা যায়নি। তথ্য যাচাই করে আবার চেষ্টা করুন।", Marathi: "साइन इन करता आले नाही. माहिती तपासून पुन्हा प्रयत्न करा.", Gujarati: "સાઇન ઇન થઈ શક્યું નથી. વિગતો તપાસીને ફરી પ્રયાસ કરો." },
  registerError: { English: "Could not create your account. Check your details and try again.", Hindi: "खाता नहीं बन सका। जानकारी जाँचकर फिर कोशिश करें।", Tamil: "கணக்கை உருவாக்க முடியவில்லை. விவரங்களைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.", Urdu: "اکاؤنٹ نہیں بن سکا۔ اپنی معلومات دیکھ کر دوبارہ کوشش کریں۔", Punjabi: "ਖਾਤਾ ਨਹੀਂ ਬਣ ਸਕਿਆ। ਜਾਣਕਾਰੀ ਜਾਂਚ ਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।", Odia: "ଖାତା ତିଆରି ହୋଇପାରିଲା ନାହିଁ। ବିବରଣୀ ଯାଞ୍ଚ କରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।", Telugu: "ఖాతా సృష్టించలేకపోయాం. వివరాలు తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.", Kannada: "ಖಾತೆ ರಚಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", Malayalam: "അക്കൗണ്ട് സൃഷ്ടിക്കാനായില്ല. വിവരങ്ങൾ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കൂ.", Bengali: "অ্যাকাউন্ট তৈরি করা যায়নি। তথ্য যাচাই করে আবার চেষ্টা করুন।", Marathi: "खाते तयार करता आले नाही. माहिती तपासून पुन्हा प्रयत्न करा.", Gujarati: "ખાતું બનાવી શકાયું નથી. વિગતો તપાસીને ફરી પ્રયાસ કરો." },
  usernameTaken: { English: "That username is already taken. Sign in or choose another username.", Hindi: "यह उपयोगकर्ता नाम पहले से लिया जा चुका है। साइन इन करें या दूसरा नाम चुनें।", Tamil: "இந்தப் பயனர்பெயர் ஏற்கனவே பயன்படுத்தப்படுகிறது. உள்நுழையவும் அல்லது வேறு பெயரைத் தேர்ந்தெடுக்கவும்.", Urdu: "یہ صارف نام پہلے سے موجود ہے۔ سائن اِن کریں یا دوسرا نام منتخب کریں۔", Punjabi: "ਇਹ ਯੂਜ਼ਰਨੇਮ ਪਹਿਲਾਂ ਹੀ ਵਰਤਿਆ ਜਾ ਰਿਹਾ ਹੈ। ਸਾਈਨ ਇਨ ਕਰੋ ਜਾਂ ਹੋਰ ਨਾਮ ਚੁਣੋ।", Odia: "ଏହି ବ୍ୟବହାରକାରୀ ନାମ ପୂର୍ବରୁ ବ୍ୟବହୃତ ହୋଇଛି। ସାଇନ୍ ଇନ୍ କରନ୍ତୁ କିମ୍ବା ଅନ୍ୟ ନାମ ବାଛନ୍ତୁ।", Telugu: "ఈ వినియోగదారు పేరు ఇప్పటికే వాడుకలో ఉంది. సైన్ ఇన్ చేయండి లేదా మరో పేరు ఎంచుకోండి.", Kannada: "ಈ ಬಳಕೆದಾರ ಹೆಸರು ಈಗಾಗಲೇ ಬಳಕೆಯಲ್ಲಿದೆ. ಸೈನ್ ಇನ್ ಮಾಡಿ ಅಥವಾ ಬೇರೆ ಹೆಸರು ಆಯ್ಕೆಮಾಡಿ.", Malayalam: "ഈ ഉപയോക്തൃനാമം ഇതിനകം ഉപയോഗത്തിലാണ്. സൈൻ ഇൻ ചെയ്യുക അല്ലെങ്കിൽ മറ്റൊരു പേര് തിരഞ്ഞെടുക്കുക.", Bengali: "এই ব্যবহারকারীর নামটি ইতিমধ্যে ব্যবহৃত হচ্ছে। সাইন ইন করুন অথবা অন্য নাম বেছে নিন।", Marathi: "हे वापरकर्तानाव आधीपासून वापरात आहे. साइन इन करा किंवा दुसरे नाव निवडा.", Gujarati: "આ વપરાશકર્તા નામ પહેલેથી વપરાય છે. સાઇન ઇન કરો અથવા બીજું નામ પસંદ કરો." },
  emailTaken: { English: "That email is already registered. Sign in or use another email.", Hindi: "यह ईमेल पहले से पंजीकृत है। साइन इन करें या दूसरा ईमेल इस्तेमाल करें।", Tamil: "இந்த மின்னஞ்சல் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது. உள்நுழையவும் அல்லது வேறு மின்னஞ்சலைப் பயன்படுத்தவும்.", Urdu: "یہ ای میل پہلے سے رجسٹرڈ ہے۔ سائن اِن کریں یا دوسری ای میل استعمال کریں۔", Punjabi: "ਇਹ ਈਮੇਲ ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰ ਹੈ। ਸਾਈਨ ਇਨ ਕਰੋ ਜਾਂ ਹੋਰ ਈਮੇਲ ਵਰਤੋ।", Odia: "ଏହି ଇମେଲ୍ ପୂର୍ବରୁ ପଞ୍ଜୀକୃତ ହୋଇଛି। ସାଇନ୍ ଇନ୍ କରନ୍ତୁ କିମ୍ବା ଅନ୍ୟ ଇମେଲ୍ ବ୍ୟବହାର କରନ୍ତୁ।", Telugu: "ఈ ఇమెయిల్ ఇప్పటికే నమోదైంది. సైన్ ఇన్ చేయండి లేదా మరో ఇమెయిల్ వాడండి.", Kannada: "ಈ ಇಮೇಲ್ ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆ. ಸೈನ್ ಇನ್ ಮಾಡಿ ಅಥವಾ ಬೇರೆ ಇಮೇಲ್ ಬಳಸಿ.", Malayalam: "ഈ ഇമെയിൽ ഇതിനകം രജിസ്റ്റർ ചെയ്തിട്ടുണ്ട്. സൈൻ ഇൻ ചെയ്യുക അല്ലെങ്കിൽ മറ്റൊരു ഇമെയിൽ ഉപയോഗിക്കുക.", Bengali: "এই ইমেলটি ইতিমধ্যে নিবন্ধিত। সাইন ইন করুন অথবা অন্য ইমেল ব্যবহার করুন।", Marathi: "हा ईमेल आधीच नोंदणीकृत आहे. साइन इन करा किंवा दुसरा ईमेल वापरा.", Gujarati: "આ ઈમેલ પહેલેથી નોંધાયેલ છે. સાઇન ઇન કરો અથવા બીજો ઈમેલ વાપરો." },
  toggleSidebar: { English: "Toggle sidebar", Hindi: "साइडबार दिखाएँ या छिपाएँ", Tamil: "பக்கப்பட்டியை மாற்று", Urdu: "سائیڈبار دکھائیں یا چھپائیں", Punjabi: "ਸਾਈਡਬਾਰ ਦਿਖਾਓ ਜਾਂ ਲੁਕਾਓ", Odia: "ସାଇଡବାର୍ ଦେଖାନ୍ତୁ କିମ୍ବା ଲୁଚାନ୍ତୁ", Telugu: "సైడ్‌బార్ చూపించు లేదా దాచు", Kannada: "ಸೈಡ್‌ಬಾರ್ ತೋರಿಸಿ ಅಥವಾ ಮರೆಮಾಡಿ", Malayalam: "സൈഡ്ബാർ കാണിക്കുക അല്ലെങ്കിൽ മറയ്ക്കുക", Bengali: "সাইডবার দেখান বা লুকান", Marathi: "साइडबार दाखवा किंवा लपवा", Gujarati: "સાઇડબાર બતાવો અથવા છુપાવો" },
  deleteConversation: { English: "Delete conversation", Hindi: "बातचीत हटाएँ", Tamil: "உரையாடலை நீக்கு", Urdu: "گفتگو حذف کریں", Punjabi: "ਗੱਲਬਾਤ ਮਿਟਾਓ", Odia: "କଥାବାର୍ତ୍ତା ହଟାନ୍ତୁ", Telugu: "సంభాషణను తొలగించు", Kannada: "ಸಂಭಾಷಣೆ ಅಳಿಸಿ", Malayalam: "സംഭാഷണം ഇല്ലാതാക്കുക", Bengali: "কথোপকথন মুছুন", Marathi: "संभाषण हटवा", Gujarati: "વાતચીત કાઢી નાખો" },
  intentDefinition: { English: "Definition", Hindi: "परिभाषा", Tamil: "வரையறை", Urdu: "تعریف", Punjabi: "ਪਰਿਭਾਸ਼ਾ", Odia: "ପରିଭାଷା", Telugu: "నిర్వచనం", Kannada: "ವ್ಯಾಖ್ಯಾನ", Malayalam: "നിർവചനം", Bengali: "সংজ্ঞা", Marathi: "व्याख्या", Gujarati: "વ્યાખ્યા" },
  intentRights: { English: "Rights", Hindi: "अधिकार", Tamil: "உரிமைகள்", Urdu: "حقوق", Punjabi: "ਅਧਿਕਾਰ", Odia: "ଅଧିକାର", Telugu: "హక్కులు", Kannada: "ಹಕ್ಕುಗಳು", Malayalam: "അവകാശങ്ങൾ", Bengali: "অধিকার", Marathi: "अधिकार", Gujarati: "અધિકારો" },
  intentProcedure: { English: "Procedure", Hindi: "प्रक्रिया", Tamil: "நடைமுறை", Urdu: "طریقۂ کار", Punjabi: "ਪ੍ਰਕਿਰਿਆ", Odia: "ପ୍ରକ୍ରିୟା", Telugu: "విధానం", Kannada: "ವಿಧಾನ", Malayalam: "നടപടിക്രമം", Bengali: "পদ্ধতি", Marathi: "प्रक्रिया", Gujarati: "પ્રક્રિયા" },
  intentComparison: { English: "Comparison", Hindi: "तुलना", Tamil: "ஒப்பீடு", Urdu: "موازنہ", Punjabi: "ਤੁਲਨਾ", Odia: "ତୁଳନା", Telugu: "పోలిక", Kannada: "ಹೋಲಿಕೆ", Malayalam: "താരതമ്യം", Bengali: "তুলনা", Marathi: "तुलना", Gujarati: "સરખામણી" },
  intentTimeline: { English: "Timeline", Hindi: "समयरेखा", Tamil: "காலவரிசை", Urdu: "تاریخی ترتیب", Punjabi: "ਸਮਾਂ-ਰੇਖਾ", Odia: "ସମୟରେଖା", Telugu: "కాలక్రమం", Kannada: "ಕಾಲಕ್ರಮ", Malayalam: "കാലക്രമം", Bengali: "সময়রেখা", Marathi: "कालरेषा", Gujarati: "સમયરેખા" },
  intentPenalty: { English: "Penalty", Hindi: "दंड", Tamil: "தண்டனை", Urdu: "سزا", Punjabi: "ਸਜ਼ਾ", Odia: "ଦଣ୍ଡ", Telugu: "శిక్ష", Kannada: "ದಂಡನೆ", Malayalam: "ശിക്ഷ", Bengali: "শাস্তি", Marathi: "दंड", Gujarati: "દંડ" },
};

const I18nContext = createContext(null);

export function I18nProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("doj_rag_ui_language");
    return UI_LANGUAGES.includes(saved) ? saved : "Auto-Detect";
  });
  const uiLanguage = language === "Auto-Detect" ? "English" : language;
  const direction = uiLanguage === "Urdu" ? "rtl" : "ltr";

  useEffect(() => {
    localStorage.setItem("doj_rag_ui_language", language);
    document.documentElement.lang = ({ English: "en", Hindi: "hi", Tamil: "ta", Urdu: "ur", Punjabi: "pa", Odia: "or", Telugu: "te", Kannada: "kn", Malayalam: "ml", Bengali: "bn", Marathi: "mr", Gujarati: "gu" })[uiLanguage] || "en";
    document.documentElement.dir = direction;
  }, [language, uiLanguage, direction]);

  const t = (key, variables = {}) => {
    const template = COPY[uiLanguage]?.[key] || EXTRA_COPY[key]?.[uiLanguage] || COPY.English[key] || EXTRA_COPY[key]?.English || key;
    return template.replace(/\{(\w+)\}/g, (_, name) => variables[name] ?? `{${name}}`);
  };

  return (
    <I18nContext.Provider value={{ language, setLanguage, uiLanguage, direction, t }}>
      {children}
    </I18nContext.Provider>
  );
}

export function useI18n() {
  const context = useContext(I18nContext);
  if (!context) throw new Error("useI18n must be used inside I18nProvider");
  return context;
}

export function getNativeLanguageName(language) {
  return NATIVE_NAMES[language] || language;
}
